### PR TITLE
Sidebar fixes and autoclose logic

### LINKED ISSUE #90: UX Close the sidebar after visiting or clicking a link (This is specially important on mobile)

### PR DESCRIPTION
**Pull request by bbtgnn**
Main changes:
- Closes #90 and #86 
- Component refactoring. Now we have:
  - `IfSidebarItem` – regulates the style of the sidebar button (may it be a link or the button for the dropdown)
  - `IfSidebarLink` and `IfSidebarDropdown` – they both contain `IfSidebarItem`, but have different functionality
  - `Sidebar` has been rewritten using the new components
  - `IfSidebarTag` – a small component used to hold the "NEW!" tag, could be reused somewhere else

### CODE REVIEW

File: components/Sidebar.tsx [hunk 1]
```diff
@@ -1,147 +1,131 @@
...
+            text: t("latest_assets"),
+            link: "/assets",
         },
         resources: {
-            name: t('imported_losh'),
-            link: '/resources',
-            tag: 'NEW'
+            text: t("imported_losh"),
+            link: "/resources",
+            tag: "NEW",
```
Comment (puria) [inline components/Sidebar.tsx:51]: i18n

**Review by puria — APPROVED** [review]
